export const PRODUCT_FETCHING = 'PRODUCT_FETCHING';
export const PRODUCT_FETCHED = 'PRODUCT_FETCHED';
export const PRODUCT_FETCHING_FAILED = 'PRODUCT_FETCHING_FAILED';

export const CREATE_PRODUCT_REQUEST =  'CREATE_PRODUCT_REQUEST';
export const CREATE_PRODUCT_ERROR =  'CREATE_PRODUCT_ERROR';
export const CREATE_PRODUCT_SUCCESS =  'CREATE_PRODUCT_SUCCESS';

