export const PRODUCT_FETCHING = 'PRODUCT_FETCHING';
export const PRODUCT_FETCHED = 'PRODUCT_FETCHED';
export const PRODUCT_FETCHING_FAILED = 'PRODUCT_FETCHING_FAILED';

export const CREATE_PRODUCT_REQUEST =  'CREATE_PRODUCT_REQUEST';
export const CREATE_PRODUCT_ERROR =  'CREATE_PRODUCT_ERROR';
export const CREATE_PRODUCT_SUCCESS =  'CREATE_PRODUCT_SUCCESS';

export const DELETE_PRODUCT_REQUEST =  'DELETE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_SUCCESS =  'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAILED =  'DELETE_PRODUCT_FAILED';

export const UPDATE_PRODUCT_REQUEST =  'UPDATE_PRODUCT_REQUEST';
export const UPDATE_PRODUCT_SUCCESS =  'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_ERROR =  'UPDATE_PRODUCT_ERROR';


// USER ACTIONS TYPES
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
